### ISSUE TITLE
Check that rustfmt was run for each pull request

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#25]

**Comment by oxr463** [comment]
```yaml
before_script:
- rustup component add clippy rustfmt
script:
- cargo fmt --all -- --check
- cargo clippy -- -D warnings
- cargo build
- cargo test
```

Taken from , [proot-me/proot-rs/.travis.yml](https://github.com/proot-me/proot-rs/blob/master/.travis.yml) (See: https://github.com/proot-me/proot-rs/issues/5).
